/// <reference lib="webworker" />
import { precacheAndRoute } from "workbox-precaching";

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by the build
precacheAndRoute(self.__WB_MANIFEST);

// Notification messages for each meal & language
const MEAL_NOTIFICATIONS: Record<string, Record<string, string>> = {
    breakfast: {
        pt: "☀️ Hora do café da manhã! Que tal gerar uma receita saudável?",
        en: "☀️ Breakfast time! How about generating a healthy recipe?",
        es: "☀️ ¡Hora del desayuno! ¿Qué tal generar una receta saludable?",
    },
    lunch: {
        pt: "🍽️ Hora do almoço! Gere uma receita com o que tem na geladeira.",
        en: "🍽️ Lunch time! Generate a recipe with what's in your fridge.",
        es: "🍽️ ¡Hora del almuerzo! Genera una receta con lo que tienes en el refrigerador.",
    },
    dinner: {
        pt: "🌙 Hora do jantar! Não esqueça de preparar algo nutritivo.",
        en: "🌙 Dinner time! Don't forget to prepare something nutritious.",
        es: "🌙 ¡Hora de cenar! No olvides preparar algo nutritivo.",
    },
};

// Listen for messages from the main app
self.addEventListener("message", (event) => {
    const data = event.data;

    if (data?.type === "SHOW_NOTIFICATION") {
        self.registration.showNotification(data.title || "🍳 Cook AI", {
            body: data.body,
            icon: "/icon.png",
            badge: "/icon.png",
            tag: data.tag || "cookai-notification",
        });
    }

    if (data?.type === "SCHEDULE_NOTIFICATIONS") {
        // The main thread handles scheduling via setTimeout.
        // This handler exists so the SW can show notifications
        // even if the page isn't focused (via SHOW_NOTIFICATION).
    }
});

// Handle push events from the server (for broadcast notifications)
self.addEventListener("push", (event) => {
    let payload: { title?: string; body?: string; icon?: string; badge?: string; tag?: string; data?: Record<string, string> } = {};

    if (event.data) {
        try {
            payload = event.data.json();
        } catch {
            payload = { body: event.data.text() };
        }
    }

    const title = payload.title || "🍳 Cook AI";
    const options: NotificationOptions = {
        body: payload.body || "Você tem uma nova notificação!",
        icon: payload.icon || "/icon.png",
        badge: payload.badge || "/icon.png",
        tag: payload.tag || `push-${Date.now()}`,
        data: payload.data || { url: "/" },
    };

    event.waitUntil(self.registration.showNotification(title, options));
});

// Handle notification click: open the app
self.addEventListener("notificationclick", (event) => {
    event.notification.close();

    const targetUrl = (event.notification.data as { url?: string })?.url || "/gerar-receitas";

    event.waitUntil(
        self.clients
            .matchAll({ type: "window", includeUncontrolled: true })
            .then((clientList) => {
                // Focus existing tab if present
                for (const client of clientList) {
                    if ("focus" in client) {
                        return client.focus();
                    }
                }
                // Otherwise open a new tab
                return self.clients.openWindow(targetUrl);
            })
    );
});

